# Generated by Django 2.2 on 2019-04-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
