# Generated by Django 2.2 on 2019-04-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
