# Generated by Django 2.2 on 2019-04-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table', '0002_tabledata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
