# Generated by Django 2.2 on 2019-04-04 20:58

import Restaurant.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('rest', models.CharField(default=Restaurant.utils.uuidToStr, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('rest', models.ForeignKey(default=Restaurant.utils.uuidToStr, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Rest')),
            ],
        ),
        migrations.CreateModel(
            name='RestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=200)),
                ('rest', models.ForeignKey(default=Restaurant.utils.uuidToStr, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Rest')),
            ],
        ),
        migrations.CreateModel(
            name='RestCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rest', models.ForeignKey(default=Restaurant.utils.uuidToStr, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Rest')),
            ],
        ),
    ]
