# Generated by Django 2.2 on 2019-04-13 23:45

import Restaurant.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.CharField(blank=True, default=Restaurant.utils.uuidToStr, max_length=100)),
                ('address', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=200)),
                ('ratings_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('price', models.CharField(max_length=10, null=True)),
                ('phone_num', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant')),
            ],
        ),
    ]
