# Generated by Django 2.2 on 2019-04-04 23:17

import Restaurant.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelp_id', models.CharField(default=Restaurant.utils.uuidToStr, max_length=100)),
                ('address', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ratings', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='restcat',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='restinfo',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='restloc',
            name='rest',
        ),
        migrations.DeleteModel(
            name='Rest',
        ),
        migrations.DeleteModel(
            name='RestCat',
        ),
        migrations.DeleteModel(
            name='RestInfo',
        ),
        migrations.DeleteModel(
            name='RestLoc',
        ),
    ]
