# Generated by Django 2.2 on 2019-04-11 18:48

import Restaurant.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20190404_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_id',
            field=models.CharField(blank=True, default=Restaurant.utils.uuidToStr, max_length=100),
        ),
    ]
