# Generated by Django 2.2 on 2019-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20190411_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ratings_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ratings_sum',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
