# Generated by Django 2.2 on 2019-04-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0004_auto_20190411_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='restaurant',
            new_name='rest',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
    ]
