# Generated by Django 2.2 on 2019-04-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0005_auto_20190411_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='rest',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
    ]
