# Generated by Django 2.2 on 2019-04-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_auto_20190411_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
    ]
