# Generated by Django 2.2 on 2019-04-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ratings_sum',
        ),
    ]
