# Generated by Django 2.2 on 2019-04-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_remove_restaurant_ratings_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_num',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
