# Generated by Django 2.2 on 2019-04-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_restaurant_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
