# Generated by Django 2.2 on 2019-04-12 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_delete_restaurantreview'),
        ('Reservation', '0002_reservationinfo_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastorderreview',
            old_name='table',
            new_name='type',
        ),
        migrations.AddField(
            model_name='pastorderreview',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant'),
        ),
    ]
