# Generated by Django 2.2 on 2019-04-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_reservationinfo_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationinfo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
