# Generated by Django 2.2 on 2019-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_auto_20190412_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastorderreview',
            name='type',
        ),
    ]
