# Generated by Django 2.2 on 2019-04-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_reservationinfo_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastorderreview',
            name='rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pastorderreview',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
