# Generated by Django 2.2 on 2019-04-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0004_auto_20190418_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastorderreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
