# Generated by Django 2.2 on 2019-04-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRatings',
        ),
    ]
